service: aws-serverless-swapi
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:us-east-2:636920964135:table/StarWarsPeople

functions:
  api:
    handler: .build/functions/basic/hello/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  swapi:
    handler: .build/functions/swapi/getSwapi/getSwapi.handler
    events:
      - httpApi:
          path: /swapi/{resource}
          method: get
  postPerson:
    handler: .build/functions/people/createPerson/createPerson.handler
    events:
      - httpApi:
          path: /people
          method: post
  getPerson:
    handler: .build/functions/people/getPerson/getPerson.handler
    events:
      - httpApi:
          path: /people
          method: get
  getOnePerson:
    handler: .build/functions/people/getOnePerson/getOnePerson.handler
    events:
      - httpApi:
          path: /people/{id}
          method: get
  updatePerson:
    handler: .build/functions/people/updatePerson/updatePerson.handler
    events:
      - httpApi:
          path: /people/{id}
          method: put
  deletePerson:
    handler: .build/functions/people/deletePerson/deletePerson.handler
    events:
      - httpApi:
          path: /people/{id}
          method: delete

resources:
  Resources:
    StarWarsPeople:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: StarWarsPeople
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH